---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.0
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(picante)
library(tidyverse)
library(sf)
library(ggtree)
library(phyloregion)
```

# species richness and phylogenetic tree

```{r code_folding=c()}
match_phylo_of_taxon_comm <- function(Chinese_species_distribution_grid_selected){
    phy <- read.tree("./phylogenetic_tree/02.tree/tree2/tree2.treefile.dated.tree_with_outgroup")
    phy$tip.label <- stringr::str_extract(phy$tip.label,'[A-Z](?=[a-z])(.+)') # Binomial names
    phy <- phytools::force.ultrametric(phy, method = 'extend')
    # convert to sparse matrix
    Chinese_species_distribution_grid_selected_sparse <- phyloregion::long2sparse(Chinese_species_distribution_grid_selected,
                                                                                  grids = 'grid_id',species = 'taxa')
    # add species has distribution to phylogeny
    species_no_phylo <- setdiff(unique(Chinese_species_distribution_grid_selected$taxa), unique(phy$tip.label))
    for (i in species_no_phylo){phy <- phytools::add.species.to.genus(phy, i)}
    phy <- phytools::add.species.to.genus(phy, species_no_phylo[1])
    # match phylogeny and species distribution matrix
    phy_match_comm <- phyloregion::match_phylo_comm(phy, Chinese_species_distribution_grid_selected_sparse,delete_empty_rows = T)
    return(phy_match_comm)
}

```

```{r code_folding=c()}
get_species_distribution_of_taxon <- function(taxon){
    # This function get terrestrial species distribution of specific taxon(i.e. mammal, ave, lizard & amphibian)
    chinese_wild_life_list <- read.csv('chinese_terrestral/chinese_wildlife_list/taxonomy.csv') %>% 
                            select('scientificName','kingdomName','phylumName','className','orderName','familyName','genusName')
    Chinese_species_distribution_grid <- read.csv("./chinese_terrestral/species_distribution_grid_filtered.csv",
                                                  header = F, col.names = c("class","species","grid_id","area")) %>% 
                                        group_by(class,species,grid_id) %>%
                                        summarise(area = sum(area)) %>%
                                        ungroup()
    # select taxon distribution
    Chinese_species_distribution_grid <- left_join(Chinese_species_distribution_grid,chinese_wild_life_list,
                                                   by = c('species' = 'scientificName'))
    Chinese_species_distribution_grid_selected <- filter(Chinese_species_distribution_grid,
                                                         class %in% taxon,
                                                         !(familyName %in% toupper(
                                                             c('Procellariidae','Alcidae','Fregatidae','Gaviidae',
                                                               'Phaethontidae','Diomedeidae','Stercorariidae','Sulidae',
                                                               'Pelecanidae','Phalacrocoracidae','Laridae','Hydrobatidae', # marine bird
                                                               'Balaenopteridae','Delphinidae','Eschrichtiidae','Ziphiidae',
                                                               'Kogiidae','Dugongidae','LIPOTIDAE','Iniidae','Phocoenidae',
                                                               'Physeteridae','Phocidae','Otariidae','Sirenia',# marine mammal
                                                               'Dermochelyidae','Cheloniidae')  # sea turtle
                                                                                     )), 
                                                         !(genusName %in% c('Emydocephalus','Hydrophis','Laticauda'))) %>%  # sea snake
                                                    as.data.frame() %>%
                                                    mutate(taxa = gsub(" ", "_", species)) %>%
                                                    dplyr::select(grid_id, taxa)
    
    return(Chinese_species_distribution_grid_selected)
}
```

## species richness

```{r}
for (i in c('amphibian','reptile','ave','mammal')){
    species_distribution_exclude_marine <- get_species_distribution_of_taxon(i)
    if (i == 'reptile'){ # add lizard distribution data from liangtao et. al. for reptile
        lizard_species_distribution_grid <- read.csv('./reptile/lizard_species_distribution_grid.csv') %>% 
                                                group_by(Binomial,id) %>%
                                                summarise(area = sum(area)) %>% 
                                                ungroup() %>% 
                                                mutate(taxa = gsub(' ', '_', Binomial), grid_id = id) %>%
                                                select(grid_id, taxa)
        species_distribution_exclude_marine <- bind_rows(species_distribution_exclude_marine, lizard_species_distribution_grid) %>% 
            distinct()
    }
    print(n_distinct(species_distribution_exclude_marine$taxa)) # number of species
    species_richness_table <- group_by(species_distribution_exclude_marine,grid_id) %>%
        summarize(richness = n_distinct(taxa))
    colnames(species_richness_table) <- ifelse(colnames(species_richness_table) != 'grid_id', # rename column
                                               paste0(i, '_', colnames(species_richness_table)),
                                               'grid_id')
    write.csv(species_richness_table, paste0('phylogenetic_result/', i, '_species_richness.csv'), row.names = F)
    # plot
    map <- left_join(species_richness_table,grid,by = c('grid_id'='id'))
    options(repr.plot.width=12, repr.plot.height=10)
    assign(paste0(i,'_richness'), 
            ggplot()+
            geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
            geom_sf(data = map,aes(fill = richness,geometry = geometry),colour='white',alpha=0.8,size=0)+
            scale_fill_distiller(palette = "Spectral")+ # fill 
            theme_bw()+
            theme(panel.grid.major=element_blank(),
                  panel.grid.minor=element_blank(),
                  plot.title = element_text(hjust = 0.5),
                 legend.position = c(0.13,0.2),
                 legend.key.size = unit(18, "pt"),
                 legend.title=element_text(size=13),
                 legend.text=element_text(size=10)))
}

```

## phylogenetic tree

```{r}
taxon_table <- get_species_distribution_of_taxon(taxon = c('amphibian','reptile','ave','mammal')) # preserve snakes
# add lizard distribution data from liangtao et. al.
lizard_species_distribution_grid  <- read.csv('./reptile/lizard_species_distribution_grid.csv') %>% 
                                        group_by(Binomial,id) %>%
                                        summarise(area = sum(area)) %>% 
                                        ungroup() %>% 
                                        mutate(taxa = gsub(' ', '_', Binomial), grid_id = id) %>%
                                        select(grid_id, taxa)

distribution_table <- bind_rows(taxon_table, lizard_species_distribution_grid)
distribution_table <- distinct(distribution_table)

matched <- match_phylo_of_taxon_comm(distribution_table)
phy <- matched$phy
# write.tree(phy, file = 'tree2.treefile.dated.tree_with_outgroup_inputed_distribution_species')
```

```{r}
label <- as.data.frame(phy$tip.label)
chinese_wild_life_list <- read.csv('chinese_terrestral/chinese_wildlife_list/taxonomy.csv') %>% 
                            select('scientificName','kingdomName','phylumName','className','orderName','familyName','genusName') %>% 
                            mutate(scientificName = gsub(' ', '_', scientificName))
colnames(label) <- c('taxa')
label <- left_join(label, chinese_wild_life_list, by = c('taxa'='scientificName'))
select(label,taxa,className) %>% 
    mutate(className = ifelse(is.na(className), 'REPTILIA', className)) %>% 
    group_by(className) %>% summarise(sum=length(taxa))

label <- select(label, taxa, orderName)
```

```{r}
# iucn_level <- read.csv('iucn_level_download.csv') %>%
#                 mutate(name = gsub(' ', '_', name))
# label_iucn_level <- left_join(label, iucn_level, by = c('taxa' = 'name')) %>%
#                     select(-X) %>%
#                     mutate(result.category = factor(result.category,
#                                                     levels = rev(c('LC', 'DD', 'NA', 'NT', 'VU', 'EN', 'CR', 'EW', 'EX'))))
# head(label_iucn_level)
```

```{r}
# ggplot(label_iucn_level,aes(x=className,fill=result.category)) +
#   geom_bar(stat="count") + scale_fill_brewer(palette = "RdYlBu", na.value="grey50") +
#     geom_text(aes(label = ..count..), position = position_stack(reverse = F, vjust = 0.7), stat = "count", colour = "black", size = 3)+
#     labs(fill = 'IUCN level')
# ggsave('Fig/IUCN_level.pdf', height = 4, width = 5, units = 'in')
```

```{r}
groupInfo <- split(label$taxa, label$orderName)
tree <- ggtree::groupOTU(phy, groupInfo)
ggtree(tree, layout="fan", ladderize = FALSE, aes(color=group)) + 
    geom_treescale()+
    theme(legend.position = "right")
ggsave('phylogenetic_result/tree2.treefile.dated.tree_with_outgroup.svg',height = 250,width = 250,units = 'mm')
```

# phyloregion

```{r}
beta_mat <- phyloregion::phylobeta(matched$comm, matched$phy)
str(beta_mat)
# where βsor is Sørensen dissimilarity,
# βsim is Simpson dissimilarity (= turnover component of Sørensen dissimilarity),
# βsne is the nestedness component of Sørensen dissimilarity
```

```{r}
optim <- optimal_phyloregion(beta_mat$phylo.beta.sim, method = "average", k = 20)
```

```{r}
str(optim)
```

```{r}
phylore <- phyloregion(beta_mat$phylo.beta.sim, k = optim$optimal$k, method = "average")
```

```{r}
str(phylore)
```

## NMDS

```{r}
nmds <- metaMDS(beta_mat$phylo.beta.sim)
nmds$stress
```

```{r}
svg("phylogenetic_result/phyloregions_NMDS.svg",height=6,width=6)
plot(
    scores(nmds, choice=c(1, 2)),
    col=c("#0072B2", "#AC84A8","#CD9CC8", "#8034FB","#FFAA33", "#FFCAA0","#BCCFB4", "#6495ED",
          "#FE6544","#E4914F","#99AEBB","#D55E00","#419BBC","#CC0033")[phylore$region.df$cluster])
text(x=0.26, y = -0.2, labels='stress value=0.137')
dev.off()
```

## phyloregion map

```{r}
region_df <- phylore$region.df %>%
                select(grids,cluster) %>%
                mutate(cluster = as.factor(cluster))
write.csv(region_df,'phylogenetic_result/phyloregion_df.csv',row.names = F)
```

```{r}
grid <- st_read("./chinese_terrestral/input/grid.shp")
china_map_std <- st_read('StandardMap_China/Base_SingleChinaRegion_GS20204615_2.shp')
china_map_std <- st_transform(china_map_std, st_crs(grid)) %>% mutate(line = tidyr::replace_na(line, 0)) %>% filter(line != 2)
```

```{r}
grid$id <- as.character(grid$id)
cluster_cut_map <- left_join(region_df,grid,by = c('grids'='id'))
options(repr.plot.width=10, repr.plot.height=8)
ggplot()+
    geom_sf(data = china_map_std,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = cluster_cut_map,aes(fill = cluster,geometry = geometry),alpha=0.7,size=0)+
    scale_fill_manual(values =c("#0072B2", "#AC84A8","#CD9CC8", "#8034FB","#FFAA33", "#FFCAA0","#BCCFB4", "#6495ED",
          "#FE6544","#E4914F","#99AEBB","#D55E00","#419BBC","#CC0033"))+ # fill 
    ggtitle("phyloregions")+
    labs(fill = "phylo realms")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
ggsave('phylogenetic_result/phyloregions.svg',width = 7, height = 7)
```

```{r}
realm <- cluster_cut_map %>% group_by(cluster) %>% summarise(geometry=st_union(geometry))
realm <- st_cast(realm$geometry, "MULTILINESTRING")
st_write(realm, 'phylogenetic_result/phyloregion/phyloregions_divider.shp',append = F)
```

```{r}
region_phylo <- as.phylo(hclust(phylore$region.dist))
region_phylo$tip.label <- c('1 Northeast China', '2 West Xinjiang', '3 East Xinjiang', '4 Sichuan - Tibet Mountains', '5 East Himalaya',
                             '6 Central China - Yunnan ', '7 Inner Mongolia Plateau', '8 North China', '9 Southeast China', '10 Hainan','11 Taiwan')

color = c("#0072B2", "#AC84A8","#CD9CC8", "#8034FB","#A354FF", "#FFCAA0","#BCCFB4" , "#F69EFF",
          "#FE6544","#E4914F","#99AEBB","#D55E00","#419BBC","#CC0033")
options(repr.plot.width=10, repr.plot.height=7)
cluster <- ggtree(region_phylo) + 
    geom_tiplab(size=7) +
    theme_tree2()+
    geom_text(aes(label=branch.length, x=branch), vjust=-.5)+
    xlim(0,0.65)
ggsave('phylogenetic_result/phyloregion_cluster.svg',cluster, width = 297, height = 150,units = 'mm')
```

# phylogenetic diversity calculating

```{r code_folding=c()}
phylogenetic_calculate <- function(taxon){
#     taxom = 'amphibian'
    library(dplyr)
    library(picante)
    library(tidyr)
    Chinese_species_distribution_grid_selected <- get_species_distribution_of_taxon(taxon)
    # transform to distribution matrix
    phy_match_comm <- match_phylo_of_taxon_comm(Chinese_species_distribution_grid_selected)
#     print(n_distinct(Chinese_species_distribution_grid_selected$taxa))
#     print(n_distinct(phy_match_comm$phy$tip.label))
#     setdiff(Chinese_species_distribution_grid_selected$taxa, unique(phy_match_comm$phy$tip.label))        
    # calculate
    phy.dist <- cophenetic(phy_match_comm$phy)
    pd <- phyloregion::PD_ses(phy_match_comm$comm, phy_match_comm$phy, model = c('tipshuffle'))
    nti <- ses.mntd(phy_match_comm$comm, phy.dist, null.model = 'taxa.labels') %>% mutate(NTI = -1*mntd.obs.z)
    nri <- ses.mpd(phy_match_comm$comm, phy.dist, null.model = 'taxa.labels') %>% mutate(NRI = -1*mpd.obs.z)

    
    # integrate results
    pd <- rename(pd, grid_id = grids)
    nti$grid_id <- row.names(nti)
    nri$grid_id <- row.names(nri)
    tmp_result <- full_join(nri, nti, by = 'grid_id') %>% full_join(pd, by = 'grid_id')
    tmp_result$grid_id <- gsub('grid_', '', tmp_result$grid_id) %>% as.numeric()
    colnames(tmp_result) <- ifelse(colnames(tmp_result) != 'grid_id', paste0(taxon, '_', colnames(tmp_result)), 'grid_id')
    write.csv(tmp_result, paste0('phylogenetic_result/', taxon, '_phylogenetic_diversity.csv'), row.names = F)
#     return(tmp_result)
}
```

```{r}
taxon <- c('amphibian','reptile','ave','mammal')

library(foreach)
library(doParallel)
print(paste0('CPUs_used:',length(taxon)))
cl <- makeCluster(length(taxon))
registerDoParallel(cl)
foreach(
    i = taxon,
    .combine = list,
    .packages = c('picante', 'dplyr', 'tidyr', 'stringr', 'phytools', 'phyloregion'),
    .verbose = T
) %dopar% phylogenetic_calculate(i)
stopCluster(cl)
```

### lizard

```{r}
# lizard_species_distribution_grid_sparse <- phyloregion::long2sparse(lizard_species_distribution_grid,
#                                                                     grids = 'grid_id',species = 'taxa')
# lizard_matched <- phyloregion::match_phylo_comm(phy, lizard_species_distribution_grid_sparse)
# n_distinct(lizard_matched$phy$tip.label)
```

```{r}
# phy.dist <- cophenetic(lizard_matched$phy)
# nti <- ses.mntd(lizard_matched$com, phy.dist, null.model = 'taxa.labels') %>% mutate(NTI = -1*mntd.obs.z)
# nri <- ses.mpd(lizard_matched$com, phy.dist, null.model = 'taxa.labels') %>% mutate(NRI = -1*mpd.obs.z)

# # integrate results
# nti$grid_id <- row.names(nti)
# nri$grid_id <- row.names(nri)
# tmp_result <- full_join(nri, nti, by = 'grid_id')
# tmp_result$grid_id <- gsub('grid_', '', tmp_result$grid_id) %>% as.numeric()
# colnames(tmp_result) <- ifelse(colnames(tmp_result) != 'grid_id', paste0('lizard_', colnames(tmp_result)), 'grid_id')
# write.csv(tmp_result, 'phylogenetic_result/lizard_phylogenetic_diversity.csv', row.names = F)

```

# phylogenetic structure map


## map layers

```{r}
grid <- st_read("./chinese_terrestral//input//grid.shp")
china_map_std <- st_read('StandardMap_China/Base_SingleChinaRegion_GS20204615_2.shp')
china_map_std <- st_transform(china_map_std, st_crs(grid)) %>% mutate(line = tidyr::replace_na(line, 0)) %>% filter(line != 2)
```

```{r}
phyloregions_line <- st_read('./phylogenetic_result/phyloregion/phyloregions_intersect.shp') %>%
                    mutate(attr = tidyr::replace_na(attr, 3)) %>% mutate(attr = as.factor(attr))
```

## plot PD, NRI and NTI

```{r}
for (i in c('amphibian','reptile','ave','mammal')){
    file <- sprintf('phylogenetic_result/%s_phylogenetic_diversity.csv', i)
    phylogenetic_result <- read.csv(file)
    phylogenetic_result_map <- left_join(phylogenetic_result, grid, by = c('grid_id'='id'))
    phylogenetic_result_map$PD <- pull(phylogenetic_result_map, get(paste0(i, '_PD_obs')))
    assign(paste0(i, '_pd'),
          ggplot()+
            geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
            geom_sf(data = phylogenetic_result_map,aes(fill = PD,geometry = geometry),colour='white',alpha=0.8,size=0)+
            scale_fill_distiller(palette = "Spectral",na.value="grey90")+ # fill 
            geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
            scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider
            scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
            labs(fill = "Faith's PD")+
            theme_bw()+
            theme(panel.grid.major=element_blank(),
                  panel.grid.minor=element_blank(),
                  plot.title = element_text(hjust = 0.5),
                 legend.position = c(0.16,0.23),
                 legend.key.size = unit(18, "pt"),
                 legend.title=element_text(size=12),
                 legend.text=element_text(size=10))
)
}
```

```{r}
for (i in c('amphibian','reptile','ave','mammal')){
    file <- sprintf('phylogenetic_result/%s_phylogenetic_diversity.csv', i)
    phylogenetic_result <- read.csv(file)
    phylogenetic_result_map <- left_join(phylogenetic_result, grid, by = c('grid_id'='id'))
    phylogenetic_result_map$ses.PD <- pull(phylogenetic_result_map, get(paste0(i, '_zscore')))
    assign(paste0(i, '_sespd'),
          ggplot()+
            geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
            geom_sf(data = phylogenetic_result_map,aes(fill = ses.PD,geometry = geometry),colour='white',alpha=0.8,size=0)+
            scale_fill_distiller(palette = "Spectral",na.value="grey90")+ # fill 
            geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
            scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider
            scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
            labs(fill = "ses.PD")+
            theme_bw()+
            theme(panel.grid.major=element_blank(),
                  panel.grid.minor=element_blank(),
                  plot.title = element_text(hjust = 0.5),
                 legend.position = c(0.16,0.23),
                 legend.key.size = unit(18, "pt"),
                 legend.title=element_text(size=12),
                 legend.text=element_text(size=10))
)
}
```

```{r}
for (i in c('amphibian','reptile','ave','mammal')){
    file <- sprintf('phylogenetic_result/%s_phylogenetic_diversity.csv', i)
    phylogenetic_result <- read.csv(file)
    phylogenetic_result_map <- left_join(phylogenetic_result, grid, by = c('grid_id'='id'))
    phylogenetic_result_map$NRI <- pull(phylogenetic_result_map, get(paste0(i, '_NRI')))
    p_nri <- ggplot()+
        geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
        geom_sf(data = phylogenetic_result_map,aes(fill = NRI, geometry = geometry),
                colour='white',alpha=0.8,size=0) +
        scale_fill_distiller(palette = "Spectral",na.value="grey90")+ # fill 
        geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
        scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider
        scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
        labs(fill = "Net Relatedness Index (NRI)")+
        theme_bw()+
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              plot.title = element_text(hjust = 0.5),
             legend.position = c(0.27,0.23),
             legend.key.size = unit(18, "pt"),
             legend.title=element_text(size=12),
             legend.text=element_text(size=10))
    assign(paste0(i, '_nri'),p)
}
```

```{r}
for (i in c('amphibian','reptile','ave','mammal')){
    file <- sprintf('phylogenetic_result/%s_phylogenetic_diversity.csv', i)
    phylogenetic_result <- read.csv(file)
    phylogenetic_result_map <- left_join(phylogenetic_result, grid, by = c('grid_id'='id'))
    phylogenetic_result_map$NTI <- pull(phylogenetic_result_map, get(paste0(i, '_NTI')))
    assign(paste0(i, '_nti'),
          ggplot()+
            geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
            geom_sf(data = phylogenetic_result_map,aes(fill = NTI,geometry = geometry),colour='white',alpha=0.8,size=0)+
            scale_fill_distiller(palette = "Spectral",na.value="grey90")+ # fill 
            geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
            scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider
            scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
            labs(fill = "Nearest Taxon Index(NTI)")+
            theme_bw()+
            theme(panel.grid.major=element_blank(),
                  panel.grid.minor=element_blank(),
                  plot.title = element_text(hjust = 0.5),
                 legend.position = c(0.25,0.23),
                 legend.key.size = unit(18, "pt"),
                 legend.title=element_text(size=12),
                 legend.text=element_text(size=10))
)
}
```

# figures

```{r}
library(png)
lizard_img <- readPNG('phyloPic/PhyloPic.02811a3f.Gopal-Murali.Lygosominae_Scincidae_Scincoidea_Scincomorpha_Sphenomorphini_Sphenomorphus_Sphenomorphus-dussumieri_Squamata_Unidentata.png')
amphibian_img <- readPNG('phyloPic/PhyloPic.4d1f2d5f.Beth-Reinke.Pelophylax_Pelophylax-perezi_Ranidae.png')
bird_img <- readPNG('phyloPic/PhyloPic.7f02b605.Lauren-Anderson.Gruidae_Gruinae_Grus_Grus-canadensis.png')
mammal_img <- readPNG('phyloPic/PhyloPic.3d259941.Margot-Michaud.Ailuropoda-melanoleuca.png')
```

```{r}
files = list.files('phylogenetic_result', pattern='_phylogenetic_diversity.csv', full.names = TRUE) 
files
phylogenetic_result <- lapply(files, read.csv) %>% Reduce(f = full_join, x = .)
```

```{r}
options(repr.plot.width=13, repr.plot.height=12)
```

```{r}
# fig_pd <- ggpubr::ggarrange(amphibian_pd, reptile_pd, ave_pd, mammal_pd, labels = c("A", "B", "C", "D"),
#                              font.label = list(size = 18), ncol = 2, nrow = 2) +
#                                 annotation_raster(amphibian_img,0.16,0.24,0.56,0.66) +                
#                                 annotation_raster(lizard_img,0.68,0.74,0.53,0.67) +
#                                 annotation_raster(bird_img,0.17,0.23,0.07,0.17) +
#                                 annotation_raster(mammal_img,0.66,0.74,0.08,0.16)
# fig_pd
# ggsave('Fig/sespd.svg',fig_pd, height = 10,width = 10,units = 'in',dpi = 300)
```

```{r}
save(amphibian_richness, reptile_richness, ave_richness, mammal_richness, fig_richness,
     file = "./Fig/richness.Rdata")
```

```{r}
fig_richness <- ggpubr::ggarrange(amphibian_richness, reptile_richness, ave_richness, mammal_richness, labels = c("A", "B", "C", "D"),
                             font.label = list(size = 18), ncol = 2, nrow = 2) +
                                annotation_raster(amphibian_img,0.16,0.24,0.56,0.66) +                
                                annotation_raster(lizard_img,0.68,0.74,0.53,0.67) +
                                annotation_raster(bird_img,0.17,0.23,0.07,0.17) +
                                annotation_raster(mammal_img,0.66,0.74,0.08,0.16)
# fig_richness
ggsave('Fig/richness.svg',fig_richness, height = 10,width = 10,units = 'in',dpi = 300)
```

```{r}
nri_taxon <- select(phylogenetic_result, ends_with('NRI')) %>% 
    pivot_longer(everything(),names_to = 'taxon', values_to = "NRI") %>% 
    mutate(taxon = gsub('_NRI', '', taxon))
nri_taxon$taxon <- factor(nri_taxon$taxon, levels = c('amphibian','reptile','ave','mammal'))
options(repr.plot.width=6, repr.plot.height=5)
nri_boxplot <- ggplot(nri_taxon, aes(x = taxon, y = NRI)) + 
    geom_boxplot()+
    theme_bw()
# ggsave('Fig/NRI_boxplot.png',height = 4,width = 5,dpi=300)
```

```{r}
# options(repr.plot.width=13, repr.plot.height=12)
# fig_nri <- ggpubr::ggarrange(amphibian_nri, reptile_nri, ave_nri, mammal_nri, labels = c("A", "B", "C", "D"),
#                              font.label = list(size = 18), ncol = 2, nrow = 2) +
#                                 annotation_raster(amphibian_img,0.16,0.24,0.56,0.66) +                
#                                 annotation_raster(lizard_img,0.68,0.74,0.53,0.67) +
#                                 annotation_raster(bird_img,0.17,0.23,0.07,0.17) +
#                                 annotation_raster(mammal_img,0.66,0.74,0.08,0.16)
# fig_nri
# ggsave('Fig/NRI.svg',fig_nri, height = 10,width = 10,units = 'in',dpi = 300)
```

```{r}
save(amphibian_nri, reptile_nri, ave_nri, mammal_nri, fig_nri,
     file = "./Fig/nri.Rdata")
```

```{r}
nti_taxon <- select(phylogenetic_result, ends_with('NTI')) %>% 
    pivot_longer(everything(),names_to = 'taxon', values_to = "NTI") %>% 
    mutate(taxon = gsub('_NTI', '', taxon))
nti_taxon$taxon <- factor(nti_taxon$taxon, levels = c('amphibian','reptile','ave','mammal'))
options(repr.plot.width=6, repr.plot.height=5)
nti_boxplot <- ggplot(nti_taxon, aes(x = taxon, y = NTI)) + 
    geom_boxplot()+
    theme_bw()
# ggsave('Fig/NTI_boxplot.png',height = 4,width = 5,dpi=300)
```

```{r}
compare_boxplot <- ggpubr::ggarrange(nri_boxplot,nti_boxplot, labels = c("A", "B"),
                             font.label = list(size = 18), ncol = 2) 
ggsave('Fig/NRI_NTI_boxplot.svg',compare_boxplot, height = 4,width = 8)
ggsave('Fig/NRI_NTI_boxplot.png',compare_boxplot,height = 4,width = 8,dpi=300)
```

```{r}
# fig_nti <- ggpubr::ggarrange(amphibian_nti, reptile_nti, ave_nti, mammal_nti, labels = c("A", "B", "C", "D"),
#                              font.label = list(size = 18), ncol = 2, nrow = 2) +
#                                 annotation_raster(amphibian_img,0.16,0.24,0.56,0.66) +                
#                                 annotation_raster(lizard_img,0.68,0.74,0.53,0.67) +
#                                 annotation_raster(bird_img,0.17,0.23,0.07,0.17) +
#                                 annotation_raster(mammal_img,0.66,0.74,0.08,0.16)
# fig_nti
# ggsave('Fig/NTI.svg',height = 10,width = 10)
```

```{r}
save(amphibian_nti, reptile_nti, ave_nti, mammal_nti, fig_nti,
     file = "./Fig/nti.Rdata")
```

```{r}
fig_amphibian <- ggpubr::ggarrange(amphibian_pd, amphibian_sespd, amphibian_nri, amphibian_nti, labels = c("A", "B", "C", "D"),
                             font.label = list(size = 18), ncol = 2, nrow = 2)
# ggsave('Fig/amphibian_phylogenetic.svg', fig_amphibian,height = 10,width = 10)
ggsave('Fig/amphibian_phylogenetic.png', fig_amphibian,height = 10,width = 10, bg = 'white')
```

```{r}
fig_reptile <- ggpubr::ggarrange(reptile_pd, reptile_sespd, reptile_nri, reptile_nti, labels = c("A", "B", "C", "D"),
                             font.label = list(size = 18), ncol = 2, nrow = 2)
# ggsave('Fig/reptile_phylogenetic.svg', fig_reptile,height = 10,width = 10)
ggsave('Fig/reptile_phylogenetic.png', fig_reptile,height = 10,width = 10, bg = 'white')
```

```{r}
fig_ave <- ggpubr::ggarrange(ave_pd, ave_sespd, ave_nri, ave_nti, labels = c("A", "B", "C", "D"),
                             font.label = list(size = 18), ncol = 2, nrow = 2)
# ggsave('Fig/ave_phylogenetic.svg', fig_ave,height = 10,width = 10)
ggsave('Fig/ave_phylogenetic.png', fig_ave,height = 10,width = 10, bg = 'white')
```

```{r}
fig_mammal <- ggpubr::ggarrange(mammal_pd, mammal_sespd, mammal_nri, mammal_nti, labels = c("A", "B", "C", "D"),
                             font.label = list(size = 18), ncol = 2, nrow = 2)
# ggsave('Fig/mammal_phylogenetic.svg', fig_mammal,height = 10,width = 10)
ggsave('Fig/mammal_phylogenetic.png', fig_mammal,height = 10,width = 10, bg = 'white')
```

```{r}
# taxon <- c('amphibian','reptile','ave','mammal')
# for (i in taxon){
    i='ave'
    taxon_distribution <- get_species_distribution_of_taxon(i)
    taxon_distribution_grid <- left_join(taxon_distribution, grid, by = c('grid_id'='id'))
#     st_write(taxon_distribution_grid, sprintf('taxon_grid_map/%s_distribution_grid.shp', i))
# }
```

```{r}
targettaxa <- filter(taxon_distribution_grid, grid_id == '5339') %>% pull(taxa)
tmp <- filter(taxon_distribution_grid, taxa %in% targettaxa) %>% 
    group_by(taxa) %>% summarise(num = n_distinct(grid_id))
```

```{r}
tmptaxa <- intersect(phy$tip.label,targettaxa)
pdf('tmp.pdf')
plot(keep.tip(phy,tmptaxa), cex = 0.22)
dev.off()
```
