---
jupyter:
  jupytext:
    formats: ipynb,md,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.0
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(tidyverse)
library(sf)
library(ragg)
```

```{r}
# lizard_map <- st_read('data_reptile/Chinese213lizards_9_27/Chinese_lizards_214_version20200927.shp')
# grid <- st_read('../chinese_terrestral/input/grid.shp')
```

```{r}
# lizard_map <- st_transform(lizard_map,crs = st_crs(grid)) %>% st_buffer(dist=0)
# inte <- st_intersection(lizard_map, grid) %>% mutate(area=st_area(geometry)) %>% 
#             st_set_geometry(NULL) %>% select(c(Group_,Binomial,id,area))
# write.csv(inte,'lizard_species_distribution_grid.csv',row.names = F) # if want to write out 'inte'
```

```{r}
lizard_species_distribution_grid  <- read.csv('lizard_species_distribution_grid.csv')
```



```{r}
grid <- st_read("../chinese_terrestral/input/grid.shp")
china_map_std <- st_read('../StandardMap_China/Base_SingleChinaRegion_GS20204615_2.shp')
china_map_std <- st_transform(china_map_std, st_crs(grid)) %>% mutate(line = tidyr::replace_na(line, 0)) %>% filter(line != 2)
phyloregions_line <- st_read('../phylogenetic_result/phyloregion/phyloregions_intersect.shp') %>%
                    mutate(attr = tidyr::replace_na(attr, 3)) %>% mutate(attr = as.factor(attr))
```

```{r}
# calculate species richness
lizards <- group_by(lizard_species_distribution_grid,id) %>% summarize(richness = length(unique(Binomial)))
map <- left_join(lizards,grid,by = 'id')
lizard_species_distribution_grid$Binomial %>% unique() %>% length()
options(repr.plot.width=12, repr.plot.height=10)
lizard_richness <- ggplot()+
    geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
    geom_sf(data = map,aes(fill = richness,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
         legend.position = c(0.13,0.2),
         legend.key.size = unit(18, "pt"),
         legend.title=element_text(size=13),
         legend.text=element_text(size=10))
lizard_richness
ggsave('lizard_species_richness.png',height = 7,width = 7,units = 'in',dpi = 300)
```

# traits data

```{r}
Biological_lizards <- read.csv('chinese_traits_lizards_corrected.csv')
Traits_of_lizards_of_the_world <- read.csv(
    "data_reptile/The_global_biogeography_of_lizard_functional_groups/Traits_of_lizards_of_the_world/Appendix_S1_Lizard_data_version_1.0.csv"
) %>% filter(Binomial %in% Biological_lizards$Species) %>% select(Binomial, diet, foraging_mode, hatchling.neonate_SVL)
    
Allen_data <- read.csv(
    'data_reptile/Allen_et_al_Amphibian_reptile_invasion_and_life_history/Allen_et_al17EL_reptile_invasion_and_life_history.csv'
) %>% mutate(Species = gsub('_', ' ', Species)) %>% filter(Species %in% Biological_lizards$Species) %>%
        select(Species, Hatchling_mass_g, Longevity_years, Sexual_maturity_age_years)

nrow(Traits_of_lizards_of_the_world)
nrow(Allen_data)

left_join(Traits_of_lizards_of_the_world, Allen_data, by = c('Binomial' = 'Species')) %>%
mutate_at(c('diet', 'foraging_mode', 'hatchling.neonate_SVL'), as.factor) %>% summary()

```

```{r}
# write.csv(chinese_traits,'chinese_traits_lizards.csv',row.names = F)
chinese_traits_corrected <- read.csv('chinese_traits_lizards_corrected.csv') %>% 
                                filter(Species %in% lizard_species_distribution_grid$Binomial)
summary(chinese_traits_corrected)
```



```{r}
chinese_traits <- column_to_rownames(chinese_traits_corrected, var = 'Species')
```

## phylosignal

```{r}
library(Rphylopars)
phy <- ape::read.tree('../tree2.treefile.dated.tree_with_outgroup_inputed_distribution_species')
phy$tip.label <- gsub('_', ' ', phy$tip.label)
matched <- picante::match.phylo.data(phy, chinese_traits)
matched$data_sub <- select(matched$data, Male_size_mm, Female_size_mm, Male_mass_g, Female_mass_g, Clutch_size,) %>% 
                mutate_all(as.numeric) %>%
                tibble::rownames_to_column('species')
                    
p_BM <- phylopars(trait_data = matched$data_sub, tree = matched$phy)
```

```{r}
summary(p_BM$anc_recon[1:nrow(matched$data_sub),])
p_lambda <- phylopars(trait_data = matched$data_sub, tree = matched$phy, model = "lambda")
p_lambda # Estimated trait covariance and Pagel's lambda; 0<lambda<1, lambda->1 means exists signal
```

```{r}
matched$data_with_rownames <- column_to_rownames(matched$data_sub, var = 'species')
p4d <- phylobase::phylo4d(matched$phy, matched$data_with_rownames)
p_lambda <- phylosignal::phyloSignal(p4d, methods = 'Lambda')
```

```{r}
phylo_sig <- bind_cols(p_lambda$stat, p_lambda$pvalue)
phylo_sig
write.csv(phylo_sig, 'phylo_sig.csv')
```

```{r}
chinese_traits_imputed <- as.data.frame(p_BM$anc_recon[1:nrow(matched$data_sub),]) %>%
                            rownames_to_column('Species') %>%
                            left_join(select(chinese_traits_corrected, Species,habitat_specialization,
                                  leg_development,
                                  reproductive_mode,
                                  habitat_use,
                                  activity_time), by = c('Species'))
summary(chinese_traits_imputed)
```

## MFA

```{r}
chinese_traits <- mutate_at(chinese_traits,
                            c('habitat_use', 'leg_development', 'reproductive_mode', 'activity_time'),as.factor) %>%
                            select(Male_size_mm,Female_size_mm,Male_mass_g,Female_mass_g,
                                  Clutch_size,
                                  habitat_specialization,
                                  leg_development,
                                  reproductive_mode,
                                  habitat_use,
                                  activity_time
                                  )
```

```{r}
chinese_traits_missmfa <- missMDA::imputeMFA(chinese_traits,
                                             group=c(4,1,1,1,1,1,1),
                                             type=c(rep('s',3),rep('n',4)))
```

```{r}
summary(chinese_traits_missmfa$completeObs)
```

```{r}
row.names(chinese_traits_missmfa$completeObs) <- row.names(chinese_traits)
```



```{r}
mfa <- FactoMineR::MFA(chinese_traits_missmfa$completeObs,
                       group=c(4,1,1,1,1,1,1),
                       type=c(rep('s',3),rep('n',4)),
                       name.group = c('body','reproduction','habitat_specialization','leg_development',
                                      'reproductive_mode','habitat_use', 'activity_time'),
                       num.group.sup = c(1,7),
                       ncp = 7)
```

```{r}
library(factoextra)
options(repr.plot.width=9,repr.plot.height=6)
eig.val <- get_eigenvalue(mfa)
p_screeplot <- fviz_screeplot(mfa,addlabels = TRUE,ncp=7,ggtheme = theme_bw())
p_screeplot
ggsave(filename = 'PCA/screeplot.png', plot = p_screeplot, height = 5,width = 7,units = 'in',dpi=300)
```

```{r}
options(repr.plot.width=16,repr.plot.height=14)
p1 <- fviz_mfa_var(mfa, "group", labelsize=3, xlim = c(-0.05,0.65), ggtheme = theme_bw()) # the correlation between groups and dimensions. red color = active groups of variables; green color = supplementary groups of variables
p2 <- fviz_mfa_var(mfa, "quanti.var", palette = "jco", 
             col.var.sup = "violet", repel = TRUE, 
            geom = c("point", "text"), legend = "none",labelsize=3, ggtheme = theme_bw()) # Correlation between quantitative variables and dimensions
# Contributions to dimension 1
p3 <- fviz_contrib(mfa, choice = "quanti.var", axes = 1, top = 10,
             palette = "jco", labelsize=3, legend = c(0.85,0.8), ggtheme = theme_bw())
# Contributions to dimension 2
p4 <- fviz_contrib(mfa, choice = "quanti.var", axes = 2, top = 10,
             palette = "jco", labelsize=3, legend = c(0.85,0.8), ggtheme = theme_bw())

p1 <- ggpubr::annotate_figure(p1,fig.lab = "A",fig.lab.size = 18)
p2 <- ggpubr::annotate_figure(p2,fig.lab = "B",fig.lab.size = 18)
p3 <- ggpubr::annotate_figure(p3,fig.lab = "C",fig.lab.size = 18)
p4 <- ggpubr::annotate_figure(p4,fig.lab = "D",fig.lab.size = 18)

pca_dimensions_plot <- ggpubr::ggarrange(p1,p2,p3,p4,ncol = 2,nrow = 2)
ggsave(filename = 'PCA/pca_dimensions.svg',plot = pca_dimensions_plot,height = 9,width = 10)
```

```{r}
# functional distribution of individual species. Individuals with similar profiles are close to each other on the factor map
options(repr.plot.width=14,repr.plot.height=12)
fviz_mfa_ind(mfa, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,legend = c(0.1,0.85), ggtheme = theme_bw())
ggsave('PCA/species_space.png',height = 10,width = 10,units = 'in',dpi=300)
```

```{r}
ind_mfa <- get_mfa_ind(mfa)$coord
head(ind_mfa)
write.csv(ind_mfa,'ind_mfa.csv')
```




# functional diversity

```{r}
# # distribution data
#long table to wide table
lizard_species_distribution_grid_selected <- dplyr::select(lizard_species_distribution_grid,id,Binomial)
lizard_species_distribution_grid_selected$occurrence <- rep(1,nrow(lizard_species_distribution_grid_selected))
lizard_species_distribution_grid_selected <- spread(lizard_species_distribution_grid_selected,Binomial,occurrence) 
lizard_species_distribution_grid_selected[is.na(lizard_species_distribution_grid_selected)] <- 0

# to matrix
lizard_species_distribution_grid_selected <- dplyr::select(lizard_species_distribution_grid_selected, 'id', row.names(ind_mfa)) %>%
                                                as.matrix()
row.names(lizard_species_distribution_grid_selected) <- lizard_species_distribution_grid_selected[,1]
lizard_species_distribution_grid_selected <- lizard_species_distribution_grid_selected[,-1]
nrow(lizard_species_distribution_grid_selected) # sites that has species
```

```{r}
row.names(ind_mfa) <- gsub(' ','_',row.names(ind_mfa))
colnames(lizard_species_distribution_grid_selected) <- gsub(' ','_',colnames(lizard_species_distribution_grid_selected))
write.csv(ind_mfa,'ind_mfa.csv',)
write.csv(lizard_species_distribution_grid_selected, "parafly/china_reptile.csv")
```

```{r}
# csv from parafly
result <- read.csv("parafly/result.csv",header = T) %>% .[seq(1,nrow(.),2),]
colnames(result) <- gsub('tmp','FD',colnames(result))
write.csv(result,"result.csv",row.names=F)
```

```{r}
result <- read.csv("result.csv",header = T)
result$i <- as.numeric(result$i)
result$FD.FRic <- as.numeric(result$FD.FRic)
result$FD.FEve <- as.numeric(result$FD.FEve)
result$FD.FDiv <- as.numeric(result$FD.FDiv)
result$FD.FDis <- as.numeric(result$FD.FDis)
```

```{r}
map <- left_join(result,grid,by = c('i'='id'))
```

```{r}
custom_theme <- theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
         legend.position = c(0.23,0.2),
         legend.key.size = unit(18, "pt"),
         legend.title=element_text(size=13),
         legend.text=element_text(size=10))

options(repr.plot.width=12, repr.plot.height=10)
lizard_FD <- ggplot()+
    geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
    geom_sf(data = map,aes(fill = FD.FRic,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral",na.value="grey90")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
    scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider 
    scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
    labs(fill = "Functional richness")+
    custom_theme
lizard_FV <- ggplot()+
    geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
    geom_sf(data = map,aes(fill = FD.FDiv,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral",na.value="grey90")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
    scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider 
    scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
    labs(fill = "Functional divergence")+
    custom_theme
lizard_FE <- ggplot()+
    geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
    geom_sf(data = map,aes(fill = FD.FEve,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral",na.value="white")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
    scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider 
    scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
    labs(fill = "Functional evenness")+
    custom_theme
```

# Functional rarity

```{r}
species_distribution_area <- group_by(lizard_species_distribution_grid, Binomial) %>%
                                summarise(grid_area = n_distinct(id)) %>% 
                                rename(species = Binomial)
head(species_distribution_area)
```

```{r}
dist_matrix <- funrar::compute_dist_matrix(ind_mfa, metric = "euclidean")
funrar <- funrar::funrar(lizard_species_distribution_grid_selected, dist_matrix, rel_abund = FALSE)
```

## distinctness

```{r}
Distinctness <- as.data.frame(funrar$Di) %>% rownames_to_column(var = 'grid_id')
Dinstinctness_long <- gather(Distinctness, key = 'species', value = 'distinctness', -grid_id) %>% filter(!is.na(distinctness))
```

```{r}
iucn_level <- read.csv('../iucn_level_download.csv') %>% dplyr::select(-X)
```

```{r}
thresold_area <- 30
top_FRic_grid <- arrange(result, desc(FD.FRic))[1:thresold_area, ] %>% pull(i)
top_FRic_species <- filter(Dinstinctness_long, grid_id %in% top_FRic_grid)  %>%
                        left_join(iucn_level, by = c('species' = 'name')) %>% 
                        left_join(species_distribution_area, by = c('species')) %>% 
                        group_by(grid_id) %>% arrange(desc(distinctness)) %>%
                        filter(grid_area < thresold_area) %>% slice(1:3) #   & result.category %in% c('VU', 'EN', 'CR', 'EX', 'EW'))
unique(top_FRic_species$species)
```

```{r}
top_FRic_species
```

## uniqueness

```{r}
head(lizard_species_distribution_grid)
```

```{r}
Ui_distribution <- dplyr::select(lizard_species_distribution_grid,id,Binomial) %>%
    filter(Binomial %in% row.names(ind_mfa)) %>% 
    left_join(funrar$Ui, by = c('Binomial' = 'species')) %>% 
    left_join(species_distribution_area, by = c('Binomial' = 'species')) %>%
    group_by(id) %>% 
    summarise(Ui_mean = sum(Ui/grid_area))   # weighted by distribution range area
Ui_map <- left_join(Ui_distribution, grid, by = c('id'))
```

```{r}
summary(Ui_distribution)
filter(funrar$Ui, Ui > 1)
```

```{r}
lizard_Ui <- ggplot()+
    geom_sf(data = china_map_std,aes(geometry = geometry),colour='black',fill='grey90',size=0.2)+
    geom_sf(data = Ui_map,aes(fill = Ui_mean,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral",na.value="#5b5b5b")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=attr,size = attr))+
    scale_color_manual(values = c('red','#F75404', 'grey60'),guide = "none")+ # delete legends of divider 
    scale_size_manual(values = c(0.8,0.6,0.5),guide = "none")+
    labs(fill = "Functional uniqueness")+
    custom_theme
```

# save picture

```{r}
options(repr.plot.width=13, repr.plot.height=12)
fig_FD <- ggpubr::ggarrange(lizard_FD, lizard_FV, lizard_FE,lizard_Ui, labels = c("A", "B", "C", "D"),
                             font.label = list(size = 18), ncol = 2, nrow = 2)
fig_FD
ggsave('fig.png',height = 10,width = 10,units = 'in',dpi=300, bg = "white")
```

```{r}
save(lizard_richness, lizard_FD, lizard_FV, lizard_FE, lizard_Ui,
     file = "lizard_FD.Rdata")
```
